In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
def dataimputer(df,a,b):
  from sklearn.impute import SimpleImputer, KNNImputer
  impute = SimpleImputer(strategy = "most_frequent")
  knnimputer = KNNImputer(n_neighbors=10)
  if len(a)!=0:
    df2 = df.iloc[:,a]
    df2 = knnimputer.fit_transform(df2)
    df2 = pd.DataFrame(df2)
  if len(b)!=0:
    df3 = df.iloc[:,b]
    df3 = impute.fit_transform(df3)
    df3 = pd.DataFrame(df3)
  i=0
  for cc in a:
    df.iloc[:,cc] = df2.iloc[:,i]
    i=i+1
  j=0
  for bb in b:
    df.iloc[:,bb] = df3.iloc[:,j]
    j=j+1
  return df

In [2]:
def nullfinder(df):
  num = []
  obj = []
  li1 = df.isnull().sum().values
  li2 = df.dtypes.values
  for a in range(0,len(df.columns)):
    if li1[a]>0:
      if li2[a]=="int" or li2[a]=="float":
        num.append(a)
      elif li2[a]=="O":
        obj.append(a)
  return num,obj

In [4]:
def normalize(df,b,a):
  from sklearn.preprocessing import OneHotEncoder
  from sklearn.preprocessing import StandardScaler
  ohe = OneHotEncoder()
  sc = StandardScaler()

  df2 = df.iloc[:,a]
  df2 = ohe.fit_transform(df2)
  df2 = pd.DataFrame(df2.toarray())

  df3 = df.iloc[:,b]
  df3 = sc.fit_transform(df3)
  df3 = pd.DataFrame(df3)

  df = pd.concat([df2,df3],axis=1)
  return df

In [5]:
def typefinder(df):
  num2 = []
  obj2 = []
  li2 = df.dtypes.values
  for a in range(0,len(df.columns)):
    if li2[a]=="int" or li2[a]=="float":
      num2.append(a)
    elif li2[a]=="O":
      obj2.append(a)
  return num2,obj2

In [41]:
train = pd.read_csv("/content/train (1).csv")
train.shape

(1460, 81)

In [42]:
y = train.iloc[:,-1]
train.drop(train.columns[-1],axis=1,inplace=True)

In [43]:
num,obj = nullfinder(train)

In [44]:
train = dataimputer(train,num,obj)

In [45]:
num2,obj2 = typefinder(train)
train = normalize(train,num2,obj2)

In [46]:
test = pd.read_csv("/content/test (1).csv")
test.shape

(1459, 80)

In [47]:
num,obj = nullfinder(test)
test = dataimputer(test,num,obj)
test.iloc[:,obj]

,MSZoning,Alley,Utilities,Exterior1st,Exterior2nd,MasVnrType,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,...,Functional,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PoolQC,Fence,MiscFeature,SaleType
0,RH,Grvl,AllPub,VinylSd,VinylSd,None,TA,TA,No,Rec,...,Typ,Gd,Attchd,Unf,TA,TA,Ex,MnPrv,Shed,WD
1,RL,Grvl,AllPub,Wd Sdng,Wd Sdng,BrkFace,TA,TA,No,ALQ,...,Typ,Gd,Attchd,Unf,TA,TA,Ex,MnPrv,Gar2,WD
2,RL,Grvl,AllPub,VinylSd,VinylSd,None,Gd,TA,No,GLQ,...,Typ,TA,Attchd,Fin,TA,TA,Ex,MnPrv,Shed,WD
3,RL,Grvl,AllPub,VinylSd,VinylSd,BrkFace,TA,TA,No,GLQ,...,Typ,Gd,Attchd,Fin,TA,TA,Ex,MnPrv,Shed,WD
4,RL,Grvl,AllPub,HdBoard,HdBoard,None,Gd,TA,No,ALQ,...,Typ,Gd,Attchd,RFn,TA,TA,Ex,MnPrv,Shed,WD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,RM,Grvl,AllPub,CemntBd,CmentBd,None,TA,TA,No,Unf,...,Typ,Gd,Attchd,Unf,TA,TA,Ex,MnPrv,Shed,WD
1455,RM,Grvl,AllPub,CemntBd,CmentBd,None,TA,TA,No,Rec,...,Typ,Gd,CarPort,Unf,TA,TA,Ex,MnPrv,Shed,WD
1456,RL,Grvl,AllPub,VinylSd,VinylSd,None,TA,TA,No,ALQ,...,Typ,TA,Detchd,Unf,TA,TA,Ex,MnPrv,Shed,WD
1457,RL,Grvl,AllPub,HdBoard,Wd Shng,None,Gd,TA,Av,GLQ,...,Typ,Gd,Attchd,Unf,TA,TA,Ex,MnPrv,Shed,WD
1458,RL,Grvl,AllPub,HdBoard,HdBoard,BrkFace,Gd,TA,Av,LwQ,...,Typ,TA,Attchd,Fin,TA,TA,Ex,MnPrv,Shed,WD

In [48]:
num2,obj2 = typefinder(test)
test = normalize(test,num2,obj2)

In [49]:
train.shape

(1460, 289)

In [50]:
test.shape

(1459, 271)

In [51]:
def regressor1(x_train,x_test,y_train):
  from sklearn.linear_model import LinearRegression
  from sklearn.tree import DecisionTreeRegressor
  from sklearn.ensemble import RandomForestRegressor  
  from sklearn.svm import SVR

  lr = LinearRegression()
  lr.fit(x_train,y_train)
  y_pred = lr.predict(x_test)
  
  dtr = DecisionTreeRegressor()
  dtr.fit(x_train,y_train)
  y_pred2 = dtr.predict(x_test)

  rfr = RandomForestRegressor()
  rfr.fit(x_train,y_train)
  y_pred3 = rfr.predict(x_test)

  svr = SVR()
  svr.fit(x_train,y_train)
  y_pred4 = svr.predict(x_test)

  return y_pred,y_pred2,y_pred3,y_pred4

In [52]:
p1,p2,p3,p4 = regressor1(train,test,y)

ValueError: ignored

In [24]:
sub = pd.read_csv("/content/sample_submission.csv")

In [27]:
te = pd.read_csv("/content/test (1).csv")
id = te.iloc[:,0]

In [29]:
submission = pd.DataFrame({"Id":id,"SalePrice":p2})

ValueError: ignored

In [30]:
id

0       1461
1       1462
2       1463
3       1464
4       1465
        ...
1454    2915
1455    2916
1456    2917
1457    2918
1458    2919
Name: Id, Length: 1459, dtype: int64

In [34]:
te

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [35]:
len(p2)

1460